import { motion, useReducedMotion } from 'framer-motion'
import { ArrowRight, Check, HeartHandshake, Leaf, Quote, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import WhatsAppFAB from '../components/WhatsAppFAB'

const themes=[['01','Cerita lama yang belum selesai'],['02','Perasaan yang pernah dipendam'],['03','Luka yang pernah diabaikan'],['04','Pengalaman yang masih tersimpan']]
const topics=[['01','Unfinished Business','Luka masa lalu yang belum selesai'],['02','Life Trap','Mengenali pola atau kebiasaan yang terus berulang'],['03','Mindful Breathing','Latihan napas sadar untuk membantu menenangkan pikiran'],['04','Menelusuri Luka Masa Lalu','Melihat kembali pengalaman dengan kesadaran'],['05','Emotional Release','Memahami dan melepaskan emosi yang selama ini tertahan']]
const outcomes=['Lebih memahami akar luka emosional','Menyadari pola emosi, kebiasaan, atau hubungan yang terbentuk dari pengalaman masa lalu','Memiliki cara yang lebih sehat untuk mengenali dan mengelola emosi','Mendapatkan latihan sederhana yang dapat dilakukan mandiri','Melangkah dengan perasaan yang lebih ringan dan lebih terhubung dengan diri sendiri']
const testimonials=[['“Saya jadi punya ruang untuk memahami apa yang selama ini saya rasakan, tanpa terburu-buru menghakimi diri sendiri.”','Peserta program'],['“Bagian yang paling berkesan adalah ketika saya belajar melihat pola lama dengan cara yang lebih lembut.”','Peserta webinar'],['“Latihan sederhana yang dibagikan terasa mudah dibawa ke keseharian saya.”','Peserta program']]
function Reveal({children,className='',delay=0}){const reduced=useReducedMotion();return <motion.div className={className} initial={reduced?false:{opacity:0,y:18}} whileInView={reduced?{}:{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.55,delay}}>{children}</motion.div>}
const SectionTitle=({eyebrow,children})=><><p className="eyebrow">{eyebrow}</p><h2 className="section-title mt-4">{children}</h2></>
export default function Home(){return <><section className="relative overflow-hidden bg-cream pt-32 sm:pt-36"><div className="hero-orb hero-orb-one" aria-hidden="true"/><div className="hero-orb hero-orb-two" aria-hidden="true"/><div className="container-max relative grid min-h-[660px] items-center gap-12 pb-20 lg:grid-cols-[1.05fr_.95fr] lg:pb-24"><Reveal><p className="eyebrow">Relung Jiwa</p><h1 className="display-title mt-5 max-w-3xl text-5xl leading-[.97] sm:text-6xl lg:text-7xl">Healing <em>From Within</em></h1><p className="mt-6 max-w-xl font-serif text-2xl leading-snug text-cocoa sm:text-3xl">Pulih dari Luka Batin, Temukan Kembali Kedamaian dalam Dirimu</p><p className="mt-6 max-w-lg text-base leading-7 text-espresso/75 sm:text-lg">Sebuah ruang reflektif untuk mengenali, memahami, dan mulai melepaskan luka emosional yang masih terbawa hingga hari ini.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a className="btn btn-coral" href="https://wa.me/6281351780173" target="_blank" rel="noreferrer">Mulai Perjalananmu <ArrowRight size={18}/></a><a className="btn btn-outline" href="#program">Pelajari Lebih Lanjut</a></div></Reveal><Reveal className="relative mx-auto w-full max-w-md lg:max-w-none" delay={.15}><div className="relative mx-auto aspect-[4/5] max-w-[470px] overflow-hidden rounded-[48%_48%_8%_8%] bg-soft-blue p-3 shadow-[0_22px_55px_rgba(41,35,33,.14)]"><img src="/assets/img/upload/Folder%20Upload%20All%20Mentor/Foto%20mentor/DSC00490.jpeg" alt="Coach Dehan dari Relung Jiwa" className="h-full w-full rounded-[45%_45%_5%_5%] object-cover"/></div><div className="absolute -bottom-5 -left-3 max-w-[210px] bg-white p-5 shadow-lg sm:-left-7"><Leaf className="mb-2 text-sage" size={22}/><p className="font-serif text-lg leading-tight text-espresso">Pelan-pelan, kamu boleh kembali pada dirimu.</p></div></Reveal></div></section>
<section className="section bg-white"><div className="container-max grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><Reveal><SectionTitle eyebrow="Ruang untuk mengenali">Pernahkah merasa…<br/>Ada sesuatu yang mengganjal, tapi tidak tahu apa?</SectionTitle></Reveal><Reveal delay={.1}><p className="max-w-xl text-lg leading-8 text-espresso/75">Kadang, apa yang kita rasakan hari ini tidak hanya tentang apa yang terjadi hari ini.</p></Reveal></div><div className="container-max mt-12 grid border-t border-cocoa/15 sm:grid-cols-2 lg:grid-cols-4">{themes.map(([n,t],i)=><Reveal key={n} delay={i*.06} className="border-b border-cocoa/15 p-6 sm:border-r lg:last:border-r-0"><span className="font-serif text-3xl text-coral">{n}</span><p className="mt-10 text-lg font-medium leading-snug">{t}</p></Reveal>)}</div></section>
<section className="section bg-soft-blue"><div className="container-max grid gap-10 lg:grid-cols-[1fr_.9fr] lg:items-center"><Reveal><SectionTitle eyebrow="Sebuah pemahaman lembut">Karena tidak semua luka datang kembali sebagai ingatan.</SectionTitle></Reveal><Reveal delay={.1}><p className="text-lg leading-8 text-espresso/75">Pengalaman masa lalu terkadang tetap hadir dalam cara kita merespons hari ini. Ia dapat terasa melalui emosi, ketakutan, atau pola hidup yang berulang.</p><div className="mt-8 flex flex-wrap gap-3">{['Emosi','Ketakutan','Pola hidup'].map(x=><span key={x} className="rounded-full border border-cocoa/20 bg-cream px-5 py-2.5 text-sm font-medium text-cocoa">{x}</span>)}</div></Reveal></div></section>
<section id="program" className="section bg-cream"><div className="container-max"><Reveal><SectionTitle eyebrow="Dalam program ini">Hal-hal yang akan kamu pelajari</SectionTitle></Reveal><div className="mt-12 divide-y divide-cocoa/15 border-y border-cocoa/15">{topics.map(([n,title,desc],i)=><Reveal key={n} delay={i*.05} className="grid gap-3 py-6 sm:grid-cols-[90px_1fr_1fr] sm:items-baseline sm:gap-8"><span className="font-serif text-3xl text-coral">{n}</span><h3 className="font-serif text-2xl text-espresso">{title}</h3><p className="leading-7 text-espresso/70">{desc}</p></Reveal>)}</div></div></section>
<section className="section bg-cocoa text-cream"><div className="container-max"><Reveal><p className="eyebrow text-sky-blue">Mengapa ini penting</p><h2 className="mt-4 max-w-4xl font-serif text-4xl leading-tight sm:text-5xl">Luka yang belum dipahami dapat memengaruhi lebih banyak bagian kehidupan daripada yang kita sadari.</h2></Reveal><div className="mt-12 grid gap-6 md:grid-cols-3">{[['Diri sendiri','Cara kita berbicara pada diri sendiri dan memahami kebutuhan personal.'],['Hubungan','Cara kita hadir, berjarak, atau membangun kedekatan dengan orang lain.'],['Aktivitas sehari-hari','Cara kita menghadapi pilihan, tekanan, dan momen-momen kecil setiap hari.']].map(([t,d],i)=><Reveal key={t} delay={i*.08} className="border-t border-cream/30 pt-5"><h3 className="font-serif text-2xl">{t}</h3><p className="mt-3 leading-7 text-cream/75">{d}</p></Reveal>)}</div></div></section>
<section className="section bg-white"><div className="container-max grid gap-12 lg:grid-cols-[.8fr_1fr] lg:items-center"><Reveal className="order-2 lg:order-1"><div className="overflow-hidden rounded-[32px_32px_32px_4px] bg-soft-blush"><img src="/assets/img/upload/Folder%20Upload%20All%20Mentor/Foto%20mentor/DSC00490.jpeg" alt="Coach Dehan" className="aspect-[4/5] w-full object-cover"/></div></Reveal><Reveal className="order-1 lg:order-2" delay={.1}><SectionTitle eyebrow="Tentang Coach Dehan">Pendampingan yang berangkat dari rasa aman.</SectionTitle><p className="mt-6 leading-8 text-espresso/75">Relung Jiwa membuka ruang untuk melihat pengalaman emosional dengan lebih sadar, hangat, dan tanpa terburu-buru. Setiap proses dimulai dari percakapan yang menghormati ritme pribadi.</p><div className="mt-7 flex items-center gap-3 text-cocoa"><HeartHandshake size={23}/><span className="font-medium">Praktisi Trauma Healing &amp; Emotional Healing</span></div><p className="mt-4 text-sm leading-6 text-espresso/60">Berpengalaman lebih dari 10 tahun mendampingi proses reflektif dan pertumbuhan personal.</p><Link to="/tentang" className="mt-8 inline-flex items-center gap-2 font-medium text-coral transition hover:text-cocoa">Kenali Relung Jiwa <ArrowRight size={17}/></Link></Reveal></div></section>
<section className="section bg-cream"><div className="container-max grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><Reveal><SectionTitle eyebrow="Membawa pulang sesuatu yang berarti">Apa yang Akan Kamu Dapatkan?</SectionTitle></Reveal><div className="space-y-4">{outcomes.map((x,i)=><Reveal key={x} delay={i*.06} className="flex gap-4 border-b border-cocoa/15 pb-4"><span className="mt-1 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-sage text-white"><Check size={15} strokeWidth={3}/></span><p className="leading-7 text-espresso/75">{x}</p></Reveal>)}</div></div></section>
<section className="section bg-soft-blush"><div className="container-max"><Reveal className="max-w-2xl"><SectionTitle eyebrow="Suara dari ruang ini">Kesan yang dibawa pulang peserta</SectionTitle></Reveal><div className="mt-10 grid gap-5 lg:grid-cols-3">{testimonials.map(([q,l],i)=><Reveal key={q} delay={i*.08} className="bg-white p-7 shadow-[0_12px_30px_rgba(41,35,33,.07)]"><Quote className="text-coral" size={28}/><blockquote className="mt-6 font-serif text-xl leading-relaxed text-espresso">{q}</blockquote><p className="mt-7 text-sm font-medium text-cocoa">— {l}</p></Reveal>)}</div></div></section>
<section className="section bg-cream"><div className="container-max"><Reveal className="relative overflow-hidden bg-cocoa px-7 py-14 text-center text-cream sm:px-12 sm:py-20"><Sparkles className="absolute left-8 top-8 text-sky-blue/80"/><p className="eyebrow text-sky-blue">Mulai dari sini</p><h2 className="mx-auto mt-4 max-w-3xl font-serif text-4xl leading-tight sm:text-5xl">Kamu tidak harus menyelesaikan semuanya hari ini.</h2><p className="mx-auto mt-5 max-w-xl text-lg text-cream/80">Tetapi kamu bisa mulai mengenali dirimu hari ini.</p><a className="btn btn-coral mt-8" href="https://wa.me/6281351780173" target="_blank" rel="noreferrer">Konsultasi <ArrowRight size={18}/></a></Reveal></div></section><WhatsAppFAB/></>}
