import { Fragment } from 'react'
import { motion, useReducedMotion } from 'framer-motion'
import { ArrowRight, Check, HeartHandshake, Leaf, Sparkles, UserRound, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import WhatsAppFAB from '../components/WhatsAppFAB'
import { useHomepage } from '../hooks/useHomepage'

const prompts = [
  ['Cerita lama yang belum selesai', 'Kenangan atau peristiwa masa lampau yang masih sering menimbulkan getaran sesak saat teringat kembali.'],
  ['Perasaan yang pernah dipendam', 'Kemarahan, kesedihan, atau kecewa yang terpaksa ditelan demi menjaga kenyamanan orang lain di sekitar.'],
  ['Luka yang pernah diabaikan', 'Upaya bersikap baik-baik saja yang lama-kelamaan menguras energi vital dan memicu kelelahan batin menahun.'],
  ['Pengalaman yang masih tersimpan', 'Pola reaksi otomatis tubuh seperti dada berdebar, pundak tegang, dan kecemasan tanpa pemicu yang nyata.'],
]
const curriculum = [
  ['Unfinished Business', 'Memahami dan mengurai luka masa lalu yang belum terselesaikan di tempat yang aman.', 'Fondasi Pemahaman'],
  ['Life Trap', 'Mengenali pola emosi berulang, reaksi defensif, dan jeratan kebiasaan yang melelahkan diri.', 'Kesadaran Pola'],
  ['Mindful Breathing & Somatic Reset', 'Latihan nafas sadar dan pelepasan somatik untuk menenangkan sistem saraf yang terus siaga.', 'Regulasi Saraf'],
  ['Menelusuri Luka Masa Lalu', 'Melihat kembali peristiwa lampau dengan kacamata kesadaran baru yang sarat kasih sayang pada diri.', 'Rekonsiliasi Batin'],
  ['Emotional Release', 'Mempraktikkan teknik katarsis lembut untuk melepaskan beban emosi yang mengendap bertahun-tahun.', 'Pelepasan Utuh'],
]
const impacts = [
  ['Diri Sendiri', 'Mempengaruhi bagaimana kita memandang harga diri, cara kita berbicara pada diri saat gagal, dan tingkat penerimaan terhadap ketidaksempurnaan.', 'Self-Compassion & Regulasi', UserRound],
  ['Hubungan Relasi', 'Mewujud dalam cara kita hadir bersama pasangan, keluarga, dan teman—apakah kita menuntut kesempurnaan atau takut membangun kedekatan emosional sejati.', 'Keintiman & Batasan Sehat', UsersRound],
  ['Aktivitas Sehari-hari', 'Berpengaruh pada daya fokus, kerentanan burnout di tempat kerja, serta cara kita membuat keputusan hidup tanpa didorong rasa panik atau takut salah.', 'Ketenangan & Produktivitas Bijak', Sparkles],
]
const benefits = [
  ['Lebih memahami akar emosi dan pemicunya', 'Mengetahui dari mana asal kecemasan atau kesedihan tanpa perlu lagi merasa bersalah atas apa yang dirasakan.'],
  ['Menyadari pola pertahanan diri dan reaksi otomatis', 'Memutus rantai kebiasaan memendam atau meledak-ledak saat menghadapi gesekan dalam hubungan interpersonal.'],
  ['Memiliki cara lebih ramah untuk mengelola emosi sulit', 'Alat bantu praktis yang terbukti ilmiah untuk meregulasi diri di tengah situasi penuh tekanan pekerjaan atau keluarga.'],
  ['Panduan latihan sederhana yang dapat dilakukan mandiri', 'Jurnal refleksi terpandu dan audio pernapasan sadar yang bisa diakses kapan pun Anda membutuhkan sauh ketenangan.'],
  ['Melangkah dengan perasaan lebih ringan dan utuh', 'Merasa kembali terkoneksi dengan tubuh, menghargai perjalanan hidup, dan menyongsong hari esok dengan harapan jernih.'],
]
const voices = [
  ['Raras W.', 'Peserta Program Introspeksi Mandiri', 'Saya jadi punya ruang untuk memahami apa yang selama ini saya rasakan, tanpa terburu-buru menghakimi diri sendiri. Ternyata tidak apa-apa untuk merasa lelah.'],
  ['Dimas A.', 'Peserta Webinar Lingkar Hening', 'Bagian yang paling berkesan adalah ketika saya belajar melihat pola lama dengan cara yang jauh lebih lembut. Pendampingan Coach Dehan terasa begitu aman dan meneduhkan.'],
  ['Siti M.', 'Konsultasi Terpandu Relung Jiwa', 'Latihan sederhana yang dibagikan terasa mudah dibawa ke keseharian saya yang padat. Sekarang, saat cemas datang, saya tahu cara untuk kembali tenang.'],
]

function Reveal({ children, className = '', delay = 0 }) { const reduced = useReducedMotion(); return <motion.div className={className} initial={reduced ? false : { opacity: 0, y: 16 }} whileInView={reduced ? {} : { opacity: 1, y: 0 }} viewport={{ once: true, amount: .16 }} transition={{ duration: .5, delay }}>{children}</motion.div> }
function CTA({ cta, label, className }) { const content = <>{label}<ArrowRight size={17} aria-hidden="true" /></>; if (cta?.type === 'internal') return <Link to={cta.path} className={className}>{content}</Link>; return <a href={cta?.url || '/kontak'} target={cta?.openInNewTab ? '_blank' : undefined} rel={cta?.openInNewTab ? 'noreferrer' : undefined} className={className}>{content}</a> }
function Multiline({ value }) { return value.split('\n').map((line, index) => <Fragment key={`${line}-${index}`}>{index > 0 && <br />}{line}</Fragment>) }

export default function Home() {
  const homepage = useHomepage()
  const primaryCTA = homepage.hero.primaryCTA || homepage.finalCTA.primaryCTA
  const heroImage = homepage.hero.image || '/assets/img/upload/Folder%20Upload%20All%20Mentor/Foto%20mentor/DSC00490.jpeg'
  const coachImage = homepage.coach.image || '/assets/img/upload/Folder%20Upload%20All%20Mentor/Foto%20mentor/DSC00490.jpeg'
  return <>
    <section className="relative overflow-hidden bg-surface pt-10 sm:pt-14"><div className="hero-orb hero-orb-one" aria-hidden="true" /><div className="container-max relative grid min-h-[600px] items-center gap-14 pb-24 lg:grid-cols-[7fr_5fr] lg:pb-28"><Reveal><p className="eyebrow inline-flex items-center gap-2 rounded-full bg-surface-container px-4 py-2"><span className="h-2 w-2 rounded-full bg-coral" />Relung Jiwa • Ruang Refleksi &amp; Pemulihan</p><h1 className="display-title mt-6 max-w-3xl">Healing <em>From Within</em> — Pulih dari Luka Batin, Temukan Kembali Kedamaian.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-espresso/70">Sebuah suaka reflektif yang aman untuk mengenali, memahami, dan memeluk luka emosional yang masih terbawa hingga hari ini secara perlahan tanpa penghakiman.</p><div className="mt-8 flex flex-wrap gap-3"><CTA cta={primaryCTA} label="Mulai Perjalananmu" className="btn btn-coral" /><a href="#kurikulum" className="btn btn-quiet">Pelajari Lebih Lanjut</a></div><div className="mt-7 flex items-center gap-3 text-sm text-espresso/60"><div className="flex -space-x-2"><span className="grid h-8 w-8 place-items-center rounded-full bg-soft-blush text-[10px] font-bold text-cocoa">RJ</span><span className="grid h-8 w-8 place-items-center rounded-full bg-soft-blue text-[10px] font-bold text-cocoa">CD</span><span className="grid h-8 w-8 place-items-center rounded-full bg-coral/20 text-[10px] font-bold text-cocoa">1k+</span></div><p>Telah mendampingi lebih dari <strong className="text-espresso">1.200+ jiwa</strong> menemukan ruang teduh.</p></div></Reveal><Reveal className="relative mx-auto w-full max-w-md pb-16 lg:max-w-none" delay={.12}><div className="relative mx-auto aspect-[4/5] max-w-[420px] overflow-hidden rounded-b-2xl rounded-t-[140px] bg-surface-container shadow-xl"><img src={heroImage} alt={homepage.hero.imageAlt || 'Coach Dehan dari Relung Jiwa'} className="h-full w-full object-cover object-top" /></div><div className="absolute bottom-0 left-0 max-w-[270px] rounded-xl bg-surface-container-lowest/95 p-4 shadow-lg backdrop-blur-sm"><div className="flex gap-2"><Leaf className="shrink-0 text-sky-blue" size={20} /><div><p className="font-serif text-[17px] italic leading-snug text-cocoa">“Pelan-pelan, kamu boleh kembali pada dirimu.”</p><p className="mt-1 text-[10px] font-semibold uppercase tracking-[.12em] text-espresso/55">Coach Dehan • Pengasuh Ruang</p></div></div></div></Reveal></div></section>

    <section className="section bg-surface-container-low"><div className="container-max"><div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div className="max-w-2xl"><p className="eyebrow text-coral">Ruang untuk Mengenali</p><h2 className="section-title mt-4">Pernahkah merasa... Ada sesuatu yang mengganjal, tapi tidak tahu apa?</h2></div><p className="max-w-sm leading-7 text-espresso/65">Kadang, apa yang kita rasakan saat ini tidak sekadar tentang apa yang baru saja terjadi hari ini.</p></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{prompts.map(([title, description], index) => <Reveal key={title} delay={index * .05} className="flex min-h-64 flex-col justify-between rounded-xl bg-surface-container-lowest p-6 shadow-sm"><span className="font-serif text-5xl text-coral/35">0{index + 1}</span><div><h3 className="font-serif text-xl text-espresso">{title}</h3><p className="mt-3 text-sm leading-6 text-espresso/60">{description}</p></div></Reveal>)}</div></div></section>

    <section className="section bg-soft-blue/55"><div className="container-max grid gap-10 lg:grid-cols-[8fr_4fr] lg:items-center"><div><p className="eyebrow text-cocoa">Sebuah Pemahaman Lembut</p><h2 className="section-title mt-4">Karena tidak semua luka datang kembali sebagai ingatan.</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-espresso/70">Pengalaman masa lalu terkadang tetap hidup dalam cara kita merespons hari ini. Ia menjelma menjadi rasa cemas tiba-tiba, kebiasaan menarik diri, atau keraguan berlebih pada kemampuan diri sendiri.</p></div><div><p className="text-sm font-semibold text-cocoa">Bentuk kehadiran luka tak kasat mata:</p><div className="mt-5 flex flex-wrap gap-2">{['Kecemasan Spontan', 'Pola Relasi Menjauh', 'People Pleasing', 'Ketegangan Fisik', 'Sulit Berkata Tidak'].map((item) => <span key={item} className="rounded-full bg-surface px-4 py-2 text-xs font-semibold text-cocoa shadow-sm">{item}</span>)}</div></div></div></section>

    <section id="kurikulum" className="section bg-surface"><div className="container-max"><div className="max-w-2xl"><p className="eyebrow text-coral">Dalam Program Ini</p><h2 className="section-title mt-4">Hal-hal yang akan kamu pelajari &amp; alami</h2><p className="mt-4 leading-7 text-espresso/65">Rangkaian modul terstruktur yang dirancang dengan ritme menenangkan, membawa pemulihan batin selangkah demi selangkah.</p></div><div className="mt-12 grid gap-3">{curriculum.map(([title, description, tag], index) => <Reveal key={title} delay={index * .04} className="flex flex-col gap-4 rounded-xl bg-surface-container-low p-5 transition hover:bg-surface-container sm:flex-row sm:items-center sm:justify-between sm:px-7"><div className="flex gap-5"><span className="font-serif text-3xl text-cocoa/70">0{index + 1}</span><div><h3 className="font-serif text-2xl text-espresso">{title}</h3><p className="mt-2 text-sm leading-6 text-espresso/60">{description}</p></div></div><span className="shrink-0 rounded-full bg-surface px-4 py-2 text-xs font-semibold text-cocoa">{tag}</span></Reveal>)}</div></div></section>

    <section className="section bg-cocoa text-cream"><div className="container-max"><div className="max-w-3xl"><p className="eyebrow text-sky-blue">Mengapa Ini Sangat Berarti</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">Luka yang belum dipahami dapat memengaruhi lebih banyak bagian kehidupan daripada yang kita sadari.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{impacts.map(([title, description, note, Icon]) => <article key={title} className="flex min-h-72 flex-col rounded-xl bg-cream/10 p-6"><Icon size={22} className="text-sky-blue" /><h3 className="mt-7 font-serif text-2xl">{title}</h3><p className="mt-3 leading-7 text-cream/80">{description}</p><p className="mt-auto pt-6 text-xs font-semibold text-sky-blue">{note}</p></article>)}</div></div></section>

    <section className="section bg-surface"><div className="container-max grid gap-12 lg:grid-cols-[5fr_7fr] lg:items-center"><div className="relative mx-auto w-full max-w-md lg:max-w-none"><div className="overflow-hidden rounded-2xl bg-surface-container shadow-md"><img src={coachImage} alt={homepage.coach.imageAlt || 'Coach Dehan'} className="aspect-[4/5] w-full object-cover" /></div><div className="absolute -bottom-4 -right-2 rounded-xl bg-surface p-4 shadow-lg sm:-right-5"><p className="font-serif text-2xl text-coral">10+ Tahun</p><p className="text-xs text-espresso/55">Mendampingi Proses Batin</p></div></div><div><p className="eyebrow text-coral">Tentang Coach Dehan</p><h2 className="section-title mt-4">Pendampingan yang berangkat dari rasa aman.</h2><p className="mt-6 text-lg leading-8 text-espresso/70">Relung Jiwa membuka ruang untuk melihat pengalaman emosional dengan lebih sadar, hangat, dan tanpa terburu-buru. Setiap proses selalu dimulai dari sebuah percakapan terbuka yang menghormati ritme pribadi Anda.</p><div className="mt-6 rounded-xl bg-surface-container-low p-5"><div className="flex gap-3"><HeartHandshake className="shrink-0 text-cocoa" size={22} /><div><p className="font-semibold text-espresso">Praktisi Trauma Healing &amp; Emotional Wellness</p><p className="mt-2 text-sm leading-6 text-espresso/60">Berpengalaman memfasilitasi ratusan lingkaran refleksi kelompok dan sesi konseling mendalam berbasis neurosains kasih sayang.</p></div></div></div><Link to="/tentang" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-cocoa hover:text-coral">Kenali Pendekatan Relung Jiwa Lebih Dekat <ArrowRight size={17} /></Link></div></div></section>

    <section className="section bg-surface-container-low"><div className="container-max grid gap-10 lg:grid-cols-[5fr_7fr]"><div><p className="eyebrow text-coral">Membawa Pulang Sesuatu yang Berarti</p><h2 className="section-title mt-4">Apa yang akan kamu rasakan setelah perjalanan ini?</h2><p className="mt-5 leading-7 text-espresso/65">Pemulihan bukan berarti melupakan segalanya, melainkan memiliki kapasitas batin baru untuk merangkul diri apa adanya.</p><blockquote className="mt-6 rounded-xl bg-surface p-5 font-serif text-lg italic leading-7 text-cocoa shadow-sm">“Saat kita berhenti berperang dengan perasaan sendiri, di situlah kedamaian mulai bertunas.”</blockquote></div><div className="grid gap-3">{benefits.map(([title, description]) => <div key={title} className="flex gap-3 rounded-lg bg-surface p-5 shadow-sm"><span className="mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-full bg-soft-blue text-cocoa"><Check size={15} strokeWidth={3} /></span><div><p className="text-sm font-semibold text-espresso">{title}</p><p className="mt-1 text-sm leading-6 text-espresso/60">{description}</p></div></div>)}</div></div></section>

    <section className="section bg-surface"><div className="container-max"><div className="mx-auto max-w-xl text-center"><p className="eyebrow text-coral">Suara dari Ruang Ini</p><h2 className="section-title mt-4">Kesan yang dibawa pulang para sahabat</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{voices.map(([name, role, quote]) => <article key={name} className="flex min-h-64 flex-col rounded-xl bg-surface-container-lowest p-6 shadow-sm"><span className="font-serif text-5xl leading-none text-coral/25">“</span><p className="mt-3 leading-7 text-espresso/70">{quote}</p><div className="mt-auto pt-6"><p className="text-sm font-semibold text-cocoa">{name}</p><p className="text-xs text-espresso/55">{role}</p></div></article>)}</div></div></section>

    <section className="overflow-hidden bg-cocoa px-5 py-16 text-center text-cream sm:px-6 sm:py-24"><div className="container-max"><p className="eyebrow text-sky-blue">Pemberhentian yang Menenangkan</p><h2 className="mx-auto mt-5 max-w-2xl font-serif text-4xl leading-tight sm:text-5xl">Kamu tidak harus menyelesaikan semuanya hari ini.</h2><p className="mx-auto mt-5 max-w-xl text-lg leading-8 text-cream/80">Tetapi kamu bisa mulai mengenali dirimu hari ini. Bersama kami, temukan kembali ruang tenang di dalam dada yang mungkin sudah lama terabaikan.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><CTA cta={homepage.finalCTA.primaryCTA || primaryCTA} label="Konsultasi Penjajakan (15 Menit)" className="btn btn-coral" /><Link to="/program" className="btn bg-white/10 text-cream hover:bg-white/20">Lihat Jadwal Program Terdekat</Link></div></div></section>
    <WhatsAppFAB />
  </>
}
